tmp<-commandArgs()
data<-read.table(tmp[6],sep="\t",header = T, row.names=1)
pdf(tmp[7],width=10,height=10,onefile=FALSE)
library(pheatmap)
annotation_col<-read.table(tmp[8]) 
#annotation = data.frame(Treat = factor(1:14%/%3,labels=c("group1","group2")))
#rownames(annotation) = colnames(data)
#Var1 = c("yellow", "blue")
#names(Var1) = c("group1", "group2")
#ann_colors = list(Treat=Var1)
pheatmap(data, cluster_rows = F,cluster_cols = T,annotation_col = annotation_col,gaps_col =10)
dev.off()
